<link rel="preconnect" href="https://yconglwkfoymamgkmtzg.supabase.co" />;

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { ThemeProvider } from "@/components/theme-providers";
import NextTopLoader from "nextjs-toploader";
import { MotionProvider } from "@/lib/providers/MotionProvider";
import { NotificationListener } from "@/lib/providers/RealtimeProvider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "GadyetHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={` ${inter.variable} antialiased `}>
        <MotionProvider>
          <NextTopLoader
            color="var(--accent)"
            showSpinner={false}
            height={3}
            shadow="none"
          />
          <ThemeProvider attribute="class" enableSystem>
            <NotificationListener />
            <main>{children}</main>
            <Toaster
              toastOptions={{
                classNames: {
                  actionButton: "!bg-accent !text-white",
                },
              }}
              richColors={true}
              expand={true}
              position="top-right"
            />
          </ThemeProvider>
        </MotionProvider>
      </body>
    </html>
  );
}
